=== graalvm/oracle-graalvm-ea-builds/schemas/generic-ea-schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://github.com/graalvm/oracle-graalvm-ea-builds/blob/main/schemas/generic-ea-schema.json",
    "title": "Generic Schema for Oracle GraalVM Early Access Builds",
    "type": "array",
    "items": {
        "title": "List of EA builds",
        "type": "object",
        "required": [
            "version",
            "latest",
            "download_base_url",
            "files"
        ],
        "additionalProperties": false,
        "properties": {
            "version": {
                "title": "The version of an EA build",
                "type": "string"
            },
            "latest": {
                "title": "Whether this is the latest EA build for this release train",
                "type": "boolean"
            },
            "download_base_url": {
                "title": "The base URL for downloading an EA build",
                "type": "string"
            },
            "files": {
                "title": "The files of an EA build",
                "type": "array",
                "items": {
                    "title": "A file of an EA build",
                    "type": "object",
                    "required": [
                        "filename",
                        "arch",
                        "platform"
                    ],
                    "additionalProperties": false,
                    "properties": {
                        "filename": {
                            "title": "The name of an EA build file",
                            "type": "string"
                        },
                        "arch": {
                            "enum": ["aarch64", "x64"],
                            "title": "The architecture of an EA build file",
                            "type": "string"
                        },
                        "platform": {
                            "enum": ["darwin", "linux", "windows"],
                            "title": "The platform of an EA build file",
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== graalvm/oracle-graalvm-ea-builds/versions/26-ea.json
[
    {
        "version": "26.0.0-ea.03",
        "latest": true,
        "download_base_url": "https://github.com/graalvm/oracle-graalvm-ea-builds/releases/download/jdk-26.0.0-ea.03/",
        "files": [
            {
                "filename": "graalvm-jdk-26.0.0-ea.03_linux-aarch64_bin.tar.gz",
                "arch": "aarch64",
                "platform": "linux"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.03_linux-x64_bin.tar.gz",
                "arch": "x64",
                "platform": "linux"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.03_windows-x64_bin.zip",
                "arch": "x64",
                "platform": "windows"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.03_macos-aarch64_bin.tar.gz",
                "arch": "aarch64",
                "platform": "darwin"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.03_macos-x64_bin.tar.gz",
                "arch": "x64",
                "platform": "darwin"
            }
        ]
    },
    {
        "version": "26.0.0-ea.02",
        "latest": false,
        "download_base_url": "https://github.com/graalvm/oracle-graalvm-ea-builds/releases/download/jdk-26.0.0-ea.02/",
        "files": [
            {
                "filename": "graalvm-jdk-26.0.0-ea.02_linux-aarch64_bin.tar.gz",
                "arch": "aarch64",
                "platform": "linux"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.02_linux-x64_bin.tar.gz",
                "arch": "x64",
                "platform": "linux"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.02_windows-x64_bin.zip",
                "arch": "x64",
                "platform": "windows"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.02_macos-aarch64_bin.tar.gz",
                "arch": "aarch64",
                "platform": "darwin"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.02_macos-x64_bin.tar.gz",
                "arch": "x64",
                "platform": "darwin"
            }
        ]
    },
    {
        "version": "26.0.0-ea.01",
        "latest": false,
        "download_base_url": "https://github.com/graalvm/oracle-graalvm-ea-builds/releases/download/jdk-26.0.0-ea.01/",
        "files": [
            {
                "filename": "graalvm-jdk-26.0.0-ea.01_linux-aarch64_bin.tar.gz",
                "arch": "aarch64",
                "platform": "linux"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.01_linux-x64_bin.tar.gz",
                "arch": "x64",
                "platform": "linux"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.01_windows-x64_bin.zip",
                "arch": "x64",
                "platform": "windows"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.01_macos-aarch64_bin.tar.gz",
                "arch": "aarch64",
                "platform": "darwin"
            },
            {
                "filename": "graalvm-jdk-26.0.0-ea.01_macos-x64_bin.tar.gz",
                "arch": "x64",
                "platform": "darwin"
            }
        ]
    }
]

=== graalvm/oracle-graalvm-ea-builds/versions/25i2-ea.json
[
    {
        "version": "25i2-25.0.3-ea.01",
        "latest": true,
        "download_base_url": "https://github.com/graalvm/oracle-graalvm-ea-builds/releases/download/jdk-25i2-25.0.3-ea.01/",
        "files": [
            {
                "filename": "graalvm-jdk-25i2-25.0.3-ea.01_linux-aarch64_bin.tar.gz",
                "arch": "aarch64",
                "platform": "linux"
            },
            {
                "filename": "graalvm-jdk-25i2-25.0.3-ea.01_linux-x64_bin.tar.gz",
                "arch": "x64",
                "platform": "linux"
            },
            {
                "filename": "graalvm-jdk-25i2-25.0.3-ea.01_windows-x64_bin.zip",
                "arch": "x64",
                "platform": "windows"
            },
            {
                "filename": "graalvm-jdk-25i2-25.0.3-ea.01_macos-aarch64_bin.tar.gz",
                "arch": "aarch64",
                "platform": "darwin"
            }
        ]
    }
]
